version: "3"

services:

  cvss-mongo:
    image: mongo:6
    command: mongod --port ${MONGO_PORT:-27017}
    restart: always
    volumes:
      - cvss-mongo-data:/data/db
    env_file:
      - ${ENV_VAR_PATH:-example.env}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:${MONGO_PORT:-27017}/cvss --quiet
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 20s
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}

  cvss:
    build: .
    image: cvss/cvss:latest

    container_name: cvss

    ports:
      - ${CVSS_PORT:-3555}:${CVSS_PORT:-3555}

    env_file:
      - ${ENV_VAR_PATH:-example.env}

    depends_on:
      cvss-mongo:
        condition: service_healthy

volumes:
  cvss-mongo-data: